name: InvisibleCanceller
main: com.ericlam.mc.main.InvisibleCanceller
version: 1.0
author: Hydranapse_
commands:
  ic-reload:
    description: reload
  ic-point:
    description: point compass
  ic-point-remove:
    description: point remove
  ic-point-nearest:
    description: point nearest
permissions:
  ic.admin:
    default: op
  ic.point:
    default: true